title: "Home"
description: "Blog · Research · Projects"
url: "https://linqi727.github.io"
baseurl: "/linqizhao.github.io"

# 使用本地主题（替代 remote_theme）
remote_theme: "mmistakes/minimal-mistakes"

locale: en-GB
repository: yourusername/yourrepo

collections:
  projects:
    output: true
    permalink: /projects/:path/

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

paginate: 5
paginate_path: "/page:num/"

minimal_mistakes_skin: default
search: true

author:
  name: "Linqi Zhao 麟琪"
  uri: "https://scholar.google.com/citations?user=qX8hUqQAAAAJ&hl=zh-CN&oi=ao"
  bio: |
    Human Computer Interaction / Game · fNIRS · PX

    <hr>

    <strong>2014–2018</strong> Sichuan University<br>
    Undergraduate Industrial Design<br>
    Supervisor: Dr Hao Wu<br><br>

    <strong>2018–2019</strong> Kuka Group<br>
    Furniture Designer<br><br>

    <strong>2020–2023</strong> Shandong University<br>
    Masters in Design<br>
    Supervisor: Dr Zhenya Wang<br><br>

    <strong>2023–</strong> University of Nottingham<br>
    PhD in Computer Science<br>
    Supervisors: Dr Horia A Maior, Dr Max L. Wilson, Dr Patrick Dickinson

  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=qX8hUqQAAAAJ&hl=zh-CN&oi=ao"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Linqi727"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      comments: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: false

include:
  - _pages

feed:
  path: feed.xml

