title: "Put Title Here"
description: "One sentence description: Blog · Project · CV"

url: "https://linqizhao.github.io"
baseurl: ""

# Use Minimal Mistakes as the remote theme
remote_theme: "mmistakes/minimal-mistakes"

# site foundation
locale: en-UK
repository: Linqi727/linqizhao.github.io

# navigation data file
collections:
projects:
output: true
permalink: /projects/:path/

# plugins
plugins:
- jekyll-include-cache
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-remote-theme

# paginate
paginate: 5
paginate_path: "/page:num/"

# author info (sidebar/mainpage visable)
author:
name: Linqi Zhao 赵麟琪
avatar: /assets/images/avatar.png # optional
bio: Research Interests / Keywords
links:
- label: GitHub
icon: "fab fa-github"
url: "https://github.com/yourusername"
- label: Google Scholar
icon: "fas fa-graduation-cap"
url: "https://scholar.google.com/citations?user=qX8hUqQAAAAJ&hl=en&oi=ao"
- label: Email
icon: "fas fa-envelope"
url: "mailto:linqi.zhao@nottingham.ac.uk"

# Social Media/SEO（optional）
social:
type: Person
name: Linqi Zhao 赵麟琪
links:
- "https://www.linkedin.com/in/linqi-zhao-771aa8345/"

# Theme Settings（adjust if needed）
minimal_mistakes_skin: default # try dark, neon, air etc.
search: true
path: feed.xml
