title: "你的站点标题"
description: "博客 · 科研进展 · 项目"
url: "http://127.0.0.1:4000"
baseurl: ""

# 使用本地主题（替代 remote_theme）
theme: "minimal-mistakes-jekyll"

locale: zh-CN
repository: yourusername/yourrepo

collections:
  projects:
    output: true
    permalink: /projects/:path/

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 5
paginate_path: "/page:num/"

minimal_mistakes_skin: default
search: true

author:
  name: 你的名字
  bio: 研究方向 / 兴趣
  links:
    - label: GitHub
      icon: "fab fa-github"
      url: "https://github.com/yourusername"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      comments: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: false

include:
  - _pages

feed:
  path: feed.xml

